//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_edit_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_edit_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\amulu\AppData\Local\Temp\4773EBEA693C6FDF1CB2202C33A3E82FDE41\2\BkEmployeePro\BkEmployeePro\views\employee\edit.cshtml"
  
    ViewBag.Title = "Edit";
    Layout= "~/views/shared/_layout.cshtml";


#line default
#line hidden

#line 2 "C:\Users\amulu\AppData\Local\Temp\4773EBEA693C6FDF1CB2202C33A3E82FDE41\2\BkEmployeePro\BkEmployeePro\views\employee\edit.cshtml"
__o = model;


#line default
#line hidden

#line 3 "C:\Users\amulu\AppData\Local\Temp\4773EBEA693C6FDF1CB2202C33A3E82FDE41\2\BkEmployeePro\BkEmployeePro\views\employee\edit.cshtml"
using (Html.BeginForm("Edit", "Employee", FormMethod.Post,new { id="Editform"}))
{
    

#line default
#line hidden

#line 4 "C:\Users\amulu\AppData\Local\Temp\4773EBEA693C6FDF1CB2202C33A3E82FDE41\2\BkEmployeePro\BkEmployeePro\views\employee\edit.cshtml"
       __o = Html.HiddenFor(u => u.EID);


#line default
#line hidden

#line 5 "C:\Users\amulu\AppData\Local\Temp\4773EBEA693C6FDF1CB2202C33A3E82FDE41\2\BkEmployeePro\BkEmployeePro\views\employee\edit.cshtml"
                       __o = Html.TextBoxFor(u => u.Name, new { @class = "form-control", placeholder = "Enter Name" });


#line default
#line hidden

#line 6 "C:\Users\amulu\AppData\Local\Temp\4773EBEA693C6FDF1CB2202C33A3E82FDE41\2\BkEmployeePro\BkEmployeePro\views\employee\edit.cshtml"
                       __o = Html.TextBoxFor(u => u.Age, new { @class = "form-control", placeholder = "Enter Age" });


#line default
#line hidden

#line 7 "C:\Users\amulu\AppData\Local\Temp\4773EBEA693C6FDF1CB2202C33A3E82FDE41\2\BkEmployeePro\BkEmployeePro\views\employee\edit.cshtml"
                       __o = Html.TextBoxFor(u => u.Qualification, new { @class = "form-control", placeholder = "Enter Qualification" });


#line default
#line hidden

#line 8 "C:\Users\amulu\AppData\Local\Temp\4773EBEA693C6FDF1CB2202C33A3E82FDE41\2\BkEmployeePro\BkEmployeePro\views\employee\edit.cshtml"
                       __o = Html.TextBoxFor(u => u.Position, new { @class = "form-control", placeholder = "Enter Position" });


#line default
#line hidden

#line 9 "C:\Users\amulu\AppData\Local\Temp\4773EBEA693C6FDF1CB2202C33A3E82FDE41\2\BkEmployeePro\BkEmployeePro\views\employee\edit.cshtml"
                       __o = Html.TextBoxFor(u => u.JoiningDate, new { @class = "form-control", placeholder = "Enter JoiningDate" });


#line default
#line hidden

#line 10 "C:\Users\amulu\AppData\Local\Temp\4773EBEA693C6FDF1CB2202C33A3E82FDE41\2\BkEmployeePro\BkEmployeePro\views\employee\edit.cshtml"
                       __o = Html.TextBoxFor(u => u.salary, new { @class = "form-control", placeholder = "Enter Salary" });


#line default
#line hidden

#line 11 "C:\Users\amulu\AppData\Local\Temp\4773EBEA693C6FDF1CB2202C33A3E82FDE41\2\BkEmployeePro\BkEmployeePro\views\employee\edit.cshtml"
          
}

#line default
#line hidden

#line 12 "C:\Users\amulu\AppData\Local\Temp\4773EBEA693C6FDF1CB2202C33A3E82FDE41\2\BkEmployeePro\BkEmployeePro\views\employee\edit.cshtml"
             __o = Url.Action("Edit", "Employee");


#line default
#line hidden
}
}
}
